[package]
name = "alloycli"
version = "0.1.0"
edition = "2021"


[dependencies]
alloy = { version = "0.1.4", features = ["full"] }
clap = { version = "4.5.9", features = ["derive"] }
eyre = "0.6.12"
tokio = "1.38.0"
